- client/web/src/organisms/mypage/layouts/HighlightAnalysisLayout.style.ts
- client/web/src/organisms/mypage/layouts/HighlightAnalysisLayout.tsx
- client/web/src/organisms/mypage/stream-analysis/StreamMetrics.tsx
- client/web/src/organisms/mypage/stream-analysis/period-analysis/PeriodAnalysisSection.style.ts
- client/web/src/organisms/mypage/stream-analysis/period-analysis/PeriodAnalysisSection.tsx
- client/web/src/organisms/mypage/stream-analysis/period-vs-period/PeriodCompareSection.tsx
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.style.ts
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.tsx
- client/web/src/organisms/shared/sub/MetricTitle.tsx
- client/web/src/organisms/shared/sub/SectionTitles.tsx
기 섹션 타이틀이 포함된 부모 컴포넌트로 분할하여 별도의 재사용가능한 컴포넌트로 분할.
대치될 기존의 섹션 타이틀 태그들의 스타일 값 삭제(사용하지 않기 때문)
- 편집점 분석 섹션 타이틀 변환
- 편집점 분석 대시보드 섹션 타이틀 변환
제플린에 올라온 웹 페이지를 참고하니 방송별 비교, 기간대 기간 분석의 하단에 **채팅 발생수 평균 비교**가 있음
_=> 현재 개발된 내용에는 해당 사항이 없어서 추가함_
- 방송별 비교: **채팅 발생수 평균 비교 추가**, 방송별 비교 섹션 타이틀 변환
- 기간 추세 분석: 기간 추세 분석 섹션 타이틀 변환
- 기간대 기간 분석: **채팅 발생수 평균 비교 추가**, 기간대 기간 분석 섹션 타이틀 변환
> 각 사이트바 탭의 섹션 타이틀 컴포넌트 재사용을 통한 통일화

- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/Calendar.tsx
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCard.tsx
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.style.ts
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.tsx
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSectioninterface.ts
- client/web/src/pages/mypage/stream-analysis/StreamAnalysis.tsx
- client/web/src/theme.tsx
- "날짜 선택" 버튼 삭제
- 기준방송과 비교방송 보여주는 방식 수정
( 회색 자리차지 → 선택하면 기준방송 또는 비교방송 자리에 카드 생성 )
- 방송분석 -> 분석하기 진행시 분석된 정보와 분석준비섹션이 겹치게 보이는 버그 수정
- theme secondary 에메랄드 색상 변경
> [TP-SPRINT #2.1] 디자인 수정 - 마이페이지:방송분석:방송별비교

- client/web/src/atoms/snackbar/ShowSnack.tsx
> 이 전에 고려하였던 레이아웃의 변경으로 인하여 스낵바의 위치가 **쌈마이**가 되었다.
- 위치를 오른쪽 상단이 아닌, 왼쪽 하단으로 변경
---
> 이전에 사용하였던 위에서 내려오는 트랜지션이 **쌈마이** 였다.
- 트랜지션을 Fade를 사용하였다.
---
- 위치를 'top', 'bottom'의 옵션을 제공하여 하단의 스낵바가 어색한 경우, 사용할 수 있도록 제공한다.
> [TP-SPRINT #2.1] 쌈마이 스낵바 수정

- client/web/src/organisms/mypage/graph/setLinearGraphComponent.ts
기간 추세 분석에서 날짜를 1개 선택해도 기본적으로 2개 날짜를 띄워주게 해놓았지만 방송이 1개인 경우에는 차트가 잘 표시되지 않는다.
- 이유
- amchart 차트에서 점 ( Bullet )을 설정해두지 않음. 생성함.
- 툴팁에 "회" 추가
- 시청자 수 인경우 "명"
> [TP-SPRINT #2.2] 방송분석 - 기간대기간 차트 렌더링 버그 수정 (1일 선택시 선,점 보이지 않는 버그)

- client/web/src/index.tsx
- client/web/src/pages/mypage/layouts/MypageLayout.tsx
- client/web/src/pages/mypage/layouts/MypageLoading.tsx
- client/web/src/utils/contexts/AuthContext.tsx
- client/web/src/utils/hooks/useAutoLogin.tsx
- client/web/src/utils/interceptors/axiosInterceptor.ts
로그인 토큰 새로고침 요청에 대한 loading 변수가 없어,
토큰이 백엔드로부터 클라이언트로 전송되기 이전에,
필수적으로 토큰이 필요한 라우터에 요청하는 경우 로그인 되어있지 않은 것으로 인식하여 메인페이지로 이동하거나, 무한 루프 요청이 발생하는 버그가 생김.
+ AuthContext에 연동된 플랫폼 고유 아이디  정보를 추가
로그인 토큰 새로고침 요청에 대한 loading State 생성 이후, 해당 state 를 참조하여
1. 기존 login 요청에 로딩 상태 값 추가
2. 토큰 refresh에 로딩 상태 값 추가
3. 로딩 중인 경우 로딩 화면 렌더링
- circularProgress 활용
4. 토큰-새로고침 완료 이전, 페이지의 렌더링 제한
> [TP-SPRINT #2.2] 로그인 token 새로고침 로딩 시 로딩 화면 렌더링 및 token 필요 데이터 요청 제한

- client/web/src/organisms/mainpage/login/LoginForm.tsx
- client/web/src/organisms/mainpage/regist/IdentityVerification.tsx
- client/web/src/organisms/mainpage/regist/style/Paper.style.ts
- client/web/src/organisms/mainpage/regist/style/RegistForm.style.ts
- client/web/src/pages/mainpage/Login.tsx
- client/web/src/pages/mainpage/Regist.tsx
- client/web/src/pages/others/FindId.tsx
- client/web/src/pages/others/FindPassword.tsx
- 기존 UI의 경우, layout의 크기를 태블릿 크기만을 기준으로 사용
> theme의 breakpoint를 구체화하여 각기 다른 layout의 크기를 적용
> 로그인 페이지 및 회원가입, ID/PW 찾기 모든 UI에 적용
> [TP-SPRINT #2.3] 로그인 및 회원가입 UI 오류 수정

- server/src/resources/category/entities/categoricalWords.entity.ts
- server/src/resources/category/entities/category.entity.ts
- shared/dto/category/categoryGet.dto.ts
- shared/interfaces/CategoricalWords.interface.ts
- shared/interfaces/Category.interface.ts
- shared/interface/ 내에 카테고리 생성
- server/resources/category 생성
> service, module등은 비어있습니다.
- categoryId
> 카테고리를 구분하는 ID
- category
> 해당 값으로 S3에서 파일을 조회 및 구분하는 영단어
- categoryName
> 사용자가 선택할 수 있도록 하는 카테고리 명
- wordId
> 단어를 구분하는 ID
- categoryId
> 카테고리를 구분짓는 ID
- word
> 단어내용
- weight
> 각 단어의 가중치
> [TP-SPRINT #2.3] 카테고리 테이블 생성

- client/web/src/organisms/mainpage/featureSuggestion/FeatureDetail.tsx
- client/web/src/organisms/mainpage/featureSuggestion/FeatureWriteForm.tsx
- client/web/src/pages/mainpage/FeatureSuggestion.tsx
- 도메인 입력창에 feature-suggestion/read/40 과 같이 입력하면 타인이 작성한 비밀글이라도 글을 열람할 수 있으므로, 밖으로 튕기도록 했으나, 자신이 작성한 글임에도 튕기는 현상 발생
- 일감 진행 중 찾은 버그
- 비밀글 상태인 글을 수정 시, 비밀글 체크 기본값이 언제나 false로 되어있어 다시 비밀글 체크를 하지 않으면 비밀글이 풀림.
1. 튕기게 하지 말고, "비밀글은 작성자만 확인할수있습니다" 표시 추가 및 목록으로 돌아가기 버튼 추가
- 이 과정에서, 볼수있는 권한이 있는지 체크 하는 방법
⇒ 비밀글아닌 경우 → 모두 보기
⇒ 비밀글인 경우 → 작성자와 본인이 동일인인지 확인 → 동일인이라면 글 렌더링
⇒ 비밀글인 경우 → 작성자와 본인이 동일인인지 확인 → 동일인 아니라면 → "비밀글은 작성자만 확인할수있습니다" 표시 추가 및 목록으로 돌아가기 버튼 렌더링
2. [수정] 클릭 시, 비밀글 여부를 기존 글의 상태에서 가져와 설정하도록 변경
> [TP-SPRINT #3.1] 비밀글 - 글 확인 불가 버그 + 비밀글 수정시 비밀글체크 항상 false인 현상 수정

- client/web/src/index.tsx
- ThemeProvider 와 SnackbarProvider 포함관계 확인.
( theme 보다 위에 있어서 생긴 문제일 가능성이 높다. )
- 다크테마에서만 존재하는 버그
> [TP-SPRINT #3.1] 다크모드 - 스낵바 렌더링 시 뒷배경 색상 제거 버그

- client/web/src/organisms/mypage/my-office/ManagePlatformLink.tsx
- client/web/src/pages/mypage/my-office/Settings.tsx
- client/web/src/utils/axios.ts
- client/web/src/utils/getApiHost.ts
- client/web/src/utils/getJosa.ts
- server/src/resources/auth/auth.controller.ts
- server/src/resources/auth/filters/afreeca-link.filter.ts
- server/src/resources/auth/filters/twitch-link.filter.ts
- server/src/resources/auth/filters/youtube-link.filter.ts
- server/src/resources/auth/strategies/afreeca.linker.ts
- server/src/resources/users/users.controller.ts
- server/src/resources/users/users.service.ts
- shared/res/LinkPlatformRes.interface.ts
연동 하려는 (트,유,아) 계정이 이미 다른 TP 유저에게 연동된 경우
다른 계정에 연동된 아이디이므로 연동 불가하여야 하며, 그것을 유저에게 알려야한다.
현재 연동하려는 (아,트,유) 0000계정은 다른 TP 계정에 연동된 계정으로 연동이 불가합니다. 문의 부탁드립니다.
→ 연동된 유저 이름 마스킹 처리하여 보여주기
> [TP-SPRINT #3.1] 동일 아이디 중복 연동 제한 기능 추가

- client/web/src/atoms/Dialog/Dialog.tsx
- client/web/src/organisms/mainpage/featureSuggestion/FeatureDetail.tsx
- client/web/src/organisms/mainpage/featureSuggestion/FeatureTable.tsx
- client/web/src/organisms/mainpage/featureSuggestion/FeatureWriteForm.tsx
- client/web/src/organisms/mainpage/featureSuggestion/sub/FeatureReply.tsx
- client/web/src/organisms/mainpage/featureSuggestion/sub/FeatureReplyInput.tsx
- client/web/src/organisms/shared/sub/HeaderLinks.tsx
- client/web/src/pages/mainpage/FeatureSuggestion.tsx
- server/src/resources/featureSuggestion/featureSuggestion.controller.ts
- server/src/resources/featureSuggestion/featureSuggestion.service.ts
1. 기능제안 history.replace 를 react-router로 수정 및 개별글 변경되지 않는 현상 수정
2. 모든 글에 대한 데이터를 한번에 불러오니 목록에서 렉걸리는 현상 발생
- 프론트
- 기능제안 목록에서는 단순 목록만(제목,날짜,비밀여부 등 컨텐츠를 제외한)
- 기능제안 개별글보기 클릭 시 해당 기능제안 데이터를 요청
- 백
- 개별글 GET controller
- 목록 GET controller
> [TP-SPRINT #3.1]기능제안 목록 렉걸리는 현상 수정 → 모든글 불러오지 않도록

- client/web/src/organisms/mypage/my-office/ManagePlatformLink.tsx
- server/src/app.module.ts
- server/src/collector-entities/afreeca/activeStreams.entity.ts
- server/src/collector-entities/afreeca/targetStreamers.entity.ts
- server/src/collector-entities/twitch/targetStreamers.entity.ts
- server/src/collector-entities/youtube/targetStreamers.entity.ts
- server/src/config/collector.database.config.ts
- server/src/config/loadConfig.ts
- server/src/interfaces/Secrets.interface.ts
- server/src/resources/auth/auth.controller.ts
- server/src/resources/auth/auth.module.ts
- server/src/resources/auth/auth.service.ts
- server/src/resources/auth/strategies/afreeca.linker.ts
- server/src/resources/auth/strategies/youtube.strategy.ts
- server/src/resources/users/users.module.ts
- server/src/resources/users/users.service.ts
트루포인트 유저가 채널 연동 시, 데이터 수집이 진행될 수 있게 CollectorDB의 타겟 유저 목록에 추가해야 한다.
아프리카 / 트위치 / 유튜브 모두.
- **백엔드 DB를 두개 연결하도록 변경한다. (multiple connection)**
- **채널 연동 시, 수집 타겟 유저 목록에 삽입 | 채널 연동 취소 시, 수집 타겟 유저 목록에서 제거**
- **CollectorDB의 경우 sync X**
---
최신 user 정보를 받아와 truepoint DB의 유저플랫폼 연동 정보를 최신화 해야한다.
- why ?
1. 유저 닉네임 불일치
2. 유저 로고 불일치
3. ...
- **프론트**
~~로그인 시, 연동정보 최신화 요청을 보낸다~~ 
**로그인 요청 시, 백엔드에서 연동 정보를 확인하고 곧바로 실행 되므로 따로 처리할 필요 없다.**
- **백엔드**
각 플랫폼 별로 연동 정보 최신화 요청을 받으면, refresh_token으로 새로운 accesstoken을 받아온다.
새로운 access Token으로 플랫폼에 유저 정보를 요청하고 최신화 한다.
- 각 플랫폼 연동 정보 유저프로필 최신화 구현
- 트위치
- 아프리카
- 유튜브
- 로그인 시 자동 처리 구현
> [TP-SPRINT #3.2] 채널 연동시 CollectorDB 데이터 수집 타겟 목록에 추가 & 로그인시 연동된 아/트/유 정보 업데이트

- client/web/src/organisms/mypage/stream-analysis/shared/PeriodStreamsList.tsx
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamList.tsx
1. 방송분석 - shared (기간 대 기간 , 기간 추이 적용)
2. 방송분석 - 방송 대 방송 적용
편집점 분석 탭 리스트에는 적용 되지 않음
( harry-stream-list-shared-router 브랜치 적용사항 이후에 적용가능 )
> [TP-SPRINT #3.2] 리스트 툴팁 "평균" 텍스트 추가

- .github/workflows/production-api-server.yml
- .github/workflows/test-api-server.yml
- client/web/src/organisms/mypage/my-office/ManagePlatformLink.tsx
- client/web/src/pages/mypage/my-office/Settings.tsx
- server/package.json
- server/src/main.ts
- server/src/resources/users/users.service.ts
- server/test.Dockerfile
- Twitch 연동 해제 X - (testtest 아이디에서 특정적으로 나타남)
- ⇒ **원인 파악**: testtest에 연동된 twitchId에 대한 정보가 PlatformTwitch 내부에 없어 생긴 문제.
1. 왜 PlatformTwtich에 없었는가? → User에 임의로 넣었기 때문으로 보임.
⇒ **수정**: PlatformTwitch 에 정보가 없으면 User에 (아/트/유)Id 제거만 진행되도록 수정
- Twitch / Youtube 연동 X - 리디렉션 URI localhost:3000 으로 설정되어 있는 문제
- ⇒ **원인 파악**:
1. test 환경에서 redirectionURI에 url이 잘못 들어가는 문제.
도커 빌드 과정 에서 NODE_ENV 주입이 올바르게 되었나 확인 필요.
⇒ 수정: API서버 github actions workflow 수정 및 API서버 Dockerfile 수정
2. 유튜브 / 트위치 redirectionURI 설정이 잘 못 되어있는 문제.
⇒ 수정: 유튜브 / 트위치 API console에서 redirectionURI 변경
- Afreeca 연동 X - 연동한 아프리카 유저가 누군지 몰라, 트루포인트 ID로 들어가도록 처리되어 있음.
- ⇒ 변경점: 아프리카 연동 방법 강구 ( 아이디를 입력 받는다거나 ) CBT 에서는 아프리카 연동 기능 없고, 참여 의사 조사시 희망 아이디를 받아 트루포인트 내부에서 아이디 생성해 주는 방식으로 진행한다고 함. 이때, 아프리카 연동도 진행 (아프리카Id를 채워 넣는다). **( 기획자로부터의 답변 )**
⇒ 수정: …
> [TP-SPRINT #3 버그수정] 채널연동 수정점

- aws/cdk/lib/prod/truepoint-collectorDB-stack.ts
트위치 채팅 수집 간헐적으로 수집되지 않는 방송이 있는 것으로 확인됨.
CloudWatch 로그 확인 결과, CPU 사용량 초과 등으로 주기적으로 꺼졌다가 켜진 것으로 보임.
- 배포하는 도커 컨테이너 CPU 최대 사용량
- 배포하는 도커 컨테이너 CPU 평균 사용량
- 트위치 채팅 수집기 ECS 서비스에 AutoScaling 기능을 추가해, 사용량이 많을 때 컨테이너를 다중으로 띄워둔다
- 이 방식에서 생길 수 있는 문제점.
1. 문제점 ⇒ Socket 서버의 양방향 연결 방식이 AutoScaling을 통해 컨테이너가 여러 개 띄워졌을 때 중복으로 연결되어 한 크리에이터의 채팅을 두번 세번 수집하지는 않을지 의문
⇒ socket.io-redis를 통해 메시지를 서로 공유하는 방식 → socket서버가아닌 socket-client인 트위치 챗봇에 올바르게 적용이 되는가?
- 일단, TwitchTargetStreamer 의 필요없는 인원은 제외하여 채팅 수집 양 자체를 줄임. ( CBT 접촉 스트리머 + channelName이 있는 스트리머 400명가량 )
- 일단, 수직 확장 진행. → 컨테이너의 CPU를 1024로 수정
- 시간대 또는 사용량에 맞추어 오토스케일링 적용은 socket 의 auto scaling 에 대하여 좀 더 공부한 뒤 진행
> [TP-SPRINT #3 버그수정] 트위치 채팅 수집 간헐적으로 수집되지 않는 방송 원인규명

- server/src/collector-entities/afreeca/targetStreamers.entity.ts
- server/src/resources/auth/auth.controller.ts
- server/src/resources/broadcast-info/broadcast-info.controller.ts
- server/src/resources/category/category.controller.ts
- server/src/resources/notification/notification.controller.ts
- server/src/resources/stream-analysis/entities/streams.entity.ts
- server/src/resources/stream-analysis/stream-analysis.controller.ts
- server/src/resources/users/users.controller.ts
- server/src/resources/users/users.service.ts
- shared/res/EditingPointListResType.interface.ts
유투브 편집점 페이지 편집점 제공 목록 요청
* GET /users/editing-point-list/:platform
* platform: 'twitch' | 'afreeca'
해당 플랫폼의 크리에이터 활동명, 가장최근방송 종료시간, 가장최근방송 제목, userId, creatorId, 플랫폼 정보를 
최근 방송종료 내림차순으로 반환합니다.
아프리카 방송의 경우 다른 db의 테이블과 조인하려 했으나 제 이해도 부족으로 실패했습니다.
지금은 AfreecaTargetStreamers 테이블에 있는 값을 Users,  PlatformAfreeca에 복붙하여 
필요한 값을 받아올 수 있게 해뒀습니다.
> Joni 최근 방송 정보 조회 (유튜브 편집점 제공 페이지) - 백엔드

- server/src/app.module.ts
- server/src/resources/rankings/entities/rankings.entity.ts
- server/src/resources/rankings/rankings.controller.ts
- server/src/resources/rankings/rankings.module.ts
- server/src/resources/rankings/rankings.service.ts
- shared/interfaces/Rankings.interface.ts
지난 월간 웃음/감탄/답답함점수 랭킹목록 반환 -> 지난 월간 웃음점수/감탄점수/답답함점수 막대그래프에 사용
* GET /rankings/monthly-scores
반응별 랭킹 top 10 -> 감탄점수, 웃음점수, 답답함점수, 욕점수 상위 10명과 10명의 최근 7개 방송 점수 데이터 반환
* GET /rankings/top-ten
플랫폼별 상위 10인 시청자수 합 비교 -> 플랫폼별 상위 10인의 시청자수 합 카드에 사용
* GET /rankings/daily-total-viewers
주간 시청자수 랭킹 -> 주간시청자 꺾은선 그래프에 사용. 최근 7일 내 날짜별 트위치, 아프리카 시청자수 상위 10인의 시청자수 총합
* GET /rankings/weekly-viewers
미흡한 사항
- 반환 타입 정의되어 있지 않음 -> 추후 프론트엔드 작업하면서 추가하겠습니다
- rankings.service안에  getWeeklyViewers 함수에서 raw쿼리 사용 -> 쿼리빌더로 작성하려고 했으나 계속 어디선가 문법 오류가 나고, 제가 그 오류를 찾지 못해서 일단 raw쿼리로 두었습니다. 더 공부한 후에 프론트 작업 하면서 수정하겠습니다
> Joni 인방 랭킹 지표 백엔드 Read

- client/web/package.json
- client/web/src/organisms/mainpage/ranking/MonthlyScoresRankingCard.tsx
- client/web/src/organisms/mainpage/ranking/UserReactionCard.tsx
- client/web/src/organisms/mainpage/ranking/WeeklyViewerRankingCard.tsx
- client/web/src/organisms/mainpage/ranking/sub/ScoresBarChart.tsx
- client/web/src/pages/mainpage/Ranking.tsx
- yarn.lock
/rankings/weekly-viewers로 요청하여 받아온 
지난 30일간의 방송에 대한 웃음 점수, 감탄 점수, 답답함 점수 상위 5인을 표시하는 막대그래프
월간 평균 막대그래프 3개 포함하는 MonthlyScoresRankingCard 컴포넌트 생성
막대그래프 개별 컴포넌트 ScoresBarChart 컴포넌트 생성
- 1, 2, 3위 에게 금/은/동 표시
- 각 크리에이터 이름이 x축
- y축의 경우 상위 5인 중 최저점수부터 표시함(0부터 표시하지 않음) 
=> 점수차를 시각적으로 더 크게 보여주기 위해서
> 인방랭킹 월간 평균 막대 차트 생성

- client/web/src/organisms/mainpage/ranking/topten/TopTenListContainer.tsx
탑텐 목록에 더보기 로딩시 목록전체가 로딩 스켈레톤으로 변경되더라구요
깜빡이는것보다 기존데이터는 남아있고
새로 들어온데이터가 붙여지는 방식이 더 깔끔한 것 같아 수정해봤습니다
> Update: 탑텐 목록 로딩 기존에 있던 데이터 까지 깜빡이지 않도록 수정

- client/web/src/organisms/mainpage/ranking/style/RatingList.style.ts
- client/web/src/organisms/mainpage/ranking/sub/RatingsListItem.tsx
- client/web/src/organisms/mainpage/ranking/topten/TopTenListContainer.tsx
탑텐 목록과 똑같이 이름을 클릭했을 때 상세 페이지로 이동하도록 추가했습니다.
>  Add: 주간 집계 시청자 평점 순위 목록의 이름을 클릭 했을 때에도 크리에이터 상세페이지로 이동 추가

- client/web/src/organisms/mainpage/ranking/topten/ScoreBar.tsx
- client/web/src/organisms/mainpage/ranking/topten/TrendsBarChart.tsx
탑텐랭킹에서 감정점수 10이 넘어가는 경우 값을 10으로 고정하도록 수정
> 감정점수 10점 이상인경우 그래프상 10의 위치에 고정

- server/src/resources/auth/auth.controller.ts
컨트롤러별 가드 사용 여부 파악 후 모든 컨트롤러에서 가드 주석처리함
**가드를 사용하고 있던 컨트롤러**
- auth.controller → 다른부분은 다 주석처리 되어있었고, 이 컨트롤러만 주석 해제되어 있었음
- broadcast-info.controller
- category.controller
- notification.controller
- stream-analysis.controller
- users.controller
> auth controller 모든 가드 주석처리

- client/web/src/organisms/mainpage/youtubeHighlight/list/PostList.tsx
- server/src/resources/broadcast-info/broadcast-info.module.ts
- server/src/resources/broadcast-info/broadcast-info.service.ts
- server/src/resources/stream-analysis/stream-analysis.service.ts
- server/src/resources/users/users.service.ts
문제상황 : 트루포인트 production 환경에서 streams, streamSummary, ranking 테이블에 데이터가 있음에도 불구하고,  편집점 분석 페이지에서 달력에 해당 방송 데이터가 표시되지 않음
원인 : typeorm sync 기능은 테이블 컬럼이 변경되었을 때 컬럼을 삭제한 뒤 새로 만듦. 그래서 기존에 입력되었던 데이터(아마 userId값)가 사라짐
현재 브랜치에서 취한 조치 : 
1. userId로 조회하는 부분에서 userId에 연동된 creatorId를 찾아서
2. Streams 테이블 조회시 where streams.userId = userId 로 조회하는 부분을 where streams.creatorId IN (twitchId,afreecaId) 로 변경함 
위 작업을 적용한 라우터
- GET /broadcast-info (편집점 분석 달력에서 사용)
- GET /user-statistics (마이페이지 대시보드 컴포넌트에서 사용)
TODO(해결하지 못한 문제):
- typeorm migration적용
- 두 라우터 제외하고 다른 부분에서 userId로 조회하는 부분을 찾아서 creatorId로 조회하도록 수정
- 유투브편집점 살펴보기 페이지에서 일부 예시화면 처럼 보이는 문제 #246
기타 수정사항
- 유투브 편집점 페이지에 나오는 목록에서 streams.needAnalysis값이 1인 방송은 제외
- 유투브 편집점 페이지에서 대시보드로 이동하는 버튼 글자를 해당 방송제목 -> '편집점 분석'으로 변경(최신 방송 제목이 뜨지 않고 있음)
> tp production DB의 Streams 테이블에서 userId컬럼이 누락되어, 데이터가 있음에도 편집점 분석 달력에 표시되지 않는 문제 수정

- client/web/src/organisms/mainpage/ranking/topten/ScoreBar.tsx
- client/web/src/organisms/mainpage/shared/ScoresSection.tsx
- server/src/resources/creatorRatings/creatorRatings.service.ts
- server/src/resources/rankings/rankings.service.ts
- shared/res/CreatorRatingResType.interface.ts
방송일 프로필 페이지 - 방송인의 1달 내 감정점수의 평균과 순위 표현 추가
— 순위 20위 이내 → (랭킹 그대로 표현)
— 상위 30% 이내인 경우 → 백분율로 표현. (ex. 상위 27%)
— 상위 30% ~ 상위 70% 인경우 → 평범한 편
— 상위 70% 이하인 경우 → 거의 없는 편
- 요청이 올 때마다 rank()함수를 사용해 순위 구하는 방식으로 만듦
- 다수 사용자를 가정하여 더 나은 방식으로 만들어야 함
> [TP #3.2] 방송 점수 상대적 위치 표현

- client/web/src/organisms/mainpage/ranking/style/TopTenCard.style.ts
- client/web/src/organisms/shared/styles/Appbar.style.tsx
탭 컴포넌트 내부 스타일 css 적용 순서가 바뀌어 레이아웃 깨진 현상 수정
> [hotfix] 탭 컴포넌트 내 스타일 깨지는 현상 수정

- client/web/src/organisms/mypage/stream-analysis/StreamMetrics.tsx
- client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.tsx
수정 전 | 수정 후 화면
- 선택된 방송 카드가 줄바뀜되는 현상 -> nowrap 속성 적용
- 결과 카드 높이가 고정이어서 글자가 보이지 않는 현상 -> 결과 카드 height 삭제
> 방송 대 방송 분석 결과 - 카드 문구 스타일 수정

- client/web/src/organisms/mainpage/communityBoard/CommunityPostWrite.tsx
- client/web/src/organisms/mainpage/communityBoard/list/PostList.tsx
- client/web/src/organisms/mainpage/communityBoard/postView/PostInfoCard.tsx
- client/web/src/organisms/mainpage/featureSuggestion/sub/FeatureReply.tsx
- client/web/src/organisms/mainpage/ranking/UserReactionCard.tsx
- client/web/src/organisms/mainpage/ranking/sub/CommentForm.tsx
- client/web/src/organisms/mainpage/ranking/sub/CommentItem.tsx
- client/web/src/organisms/mainpage/ranking/sub/UserReactionListItem.tsx
- client/web/src/utils/checkAvailableNickname.ts
- server/.adminbro/.entry.js
- server/src/admin-panel/admin-panel.options.ts
- server/src/admin-panel/components/child-comment-for-creator-comment.tsx
- server/src/admin-panel/components/child-comment-for-post-comment.tsx
- server/src/admin-panel/components/comment-for-post.tsx
- server/src/admin-panel/config.ts
- server/src/admin-panel/resources/community-post.resource.ts
- server/src/admin-panel/resources/community-reply.resource.ts
- server/src/admin-panel/resources/creatorComments.resource.ts
- server/src/admin-panel/resources/featurSuggestionReply.resource.ts
- server/src/resources/communityBoard/communityBoard.controller.ts
- server/src/resources/userReaction/entities/userReaction.entity.ts
- shared/interfaces/UserReaction.interface.ts
트포 웹 닉네임 입력 가능한 곳에서 ['관리자', 'Truepoint'] 를 닉네임으로 입력 시, 사용할 수 없는 닉네임이라는  스낵바 띄움
- 잡담방
- 자유게시판
- 방송인 프로필 페이지 댓글
- 자유게시판 댓글
관리자페이지(Truepoint 관리자 웹 > db admin으로 이동)에서 '관리자' 닉네임으로 작성 가능하도록 수정
- 잡담방 - `잡담방 > Create New 클릭` 닉네임 자유 입력 가능, userId에 Truepoint 입력할것
- 자유게시판 글 -  `자유게시판 글 > Create New 클릭` 닉네임 자유 입력 가능, userId에 Truepoint 입력할것
- 자유게시판 댓글 - `자유게시판 글 > 댓글달 글 클릭` 닉네임 '관리자' 고정
- 자유게시판 대댓글 - `자유게시판 댓글 > 대댓글 달 댓글 클릭` 닉네임 '관리자' 고정
- 방송인 프로필 페이지 대댓글 - `방송인 프로필 페이지 댓글 > 대댓글 달 댓글 클릭` 닉네임 '관리자' 고정
> [tp 3.22] 닉네임 입력칸에 특정 이름('관리자') 사용 제한

- client/web/src/organisms/mainpage/login/FindIdForm.tsx
- client/web/src/pages/others/GetTemporaryPassword.tsx
- server/src/resources/users/users.controller.ts
- server/src/resources/users/users.service.ts
회원가입 화면에서 '이름' 입력칸 삭제함에 변경되어야 할 부분 수정
- 아이디 찾기에서 '이름' 입력칸 삭제
- 비밀번호 찾기에서 '이름' 입력칸 삭제
- 아이디 찾기(/users/id) 핸들러에서 name 파라미터 삭제
- 유저 존재여부 확인(/users/check-exist-user) 핸들러에서 name 파라미터 삭제
> [수정요청] 아이디, 비밀번호 찾기 시 '이름' 입력칸 삭제
