client/web/src/organisms/mypage/stream-analysis/StreamMetrics.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCard.tsx, client/web/src/organisms/shared/Appbar.tsx
=> <버그수정> [TP-SPRINT #2.1] 디자인 수정 - 마이페이지:방송분석:방송별비교

client/web/src/atoms/Dialog/Dialog.tsx, client/web/src/atoms/Dialog/ShowDialog.tsx, client/web/src/organisms/mainpage/main/inquiry/Inquiry.tsx, client/web/src/organisms/mainpage/main/productHero/ProductHero.tsx
[TP-SPRINT #2.1] confirm 대신 사용할 Dialog 컴포넌트 생성 - (재사용성을 갖춘)
https://www.notion.so/whiletrue/TP-SPRINT-2-1-confirm-Dialog-930950f4f67c4fbfb9ded71a7613ebee
=> [TP-SPRINT #2.1] 확장성을 위한 dialog 구현 완료

client/web/src/atoms/Table/MaterialTable.tsx, client/web/src/organisms/mainpage/featureSuggestion/FeatureTable.tsx, client/web/src/organisms/mainpage/featureSuggestion/FeatureWriteForm.tsx, server/src/resources/featureSuggestion/entities/featureSuggestion.entity.ts, server/src/resources/featureSuggestion/featureSuggestion.service.ts, shared/dto/featureSuggestion/featureSuggestionPatch.dto.ts, shared/dto/featureSuggestion/featureSuggestionPost.dto.ts, shared/interfaces/FeatureSuggestion.interface.ts
- backend entity - 비밀글 여부 추가
- 기능제안 컨트롤러, 서비스 비밀글 관련 추가
- 비밀글 Entity 추가
- `isLock: boolean`, 기본값 `false`
- 기능제안 글 생성, 수정 DTO 수정
- 기능제안 글 생성, 수정 시 isLock 함께 생성, 수정되도록 추가
- 추가적으로 진행한 일감
- 기능제안 FeatureTable 컴포넌트 명 수정 (파일명과 다르게 컴포넌트명은 그냥 Table 이었음. )
⇒ Table → FeatureTable
- FeatureTable에서 사용하는 원시 컴포넌트 atoms/Table/MaterialTable 의 타입에러 수정
테이블 Row의 각 프로퍼티의 값에 대한 타입이 잘못 표기되어 있었다 (unknown ⇒ any 로 수정)
=> [TP-SPRINT #2.3] 기능제안 글쓰기 비밀글 기능추가

client/web/src/organisms/mainpage/featureSuggestion/FeatureDetail.tsx, client/web/src/organisms/mainpage/featureSuggestion/FeatureTable.tsx, client/web/src/organisms/mainpage/featureSuggestion/FeatureWriteForm.tsx, client/web/src/pages/mainpage/FeatureSuggestion.tsx, server/src/resources/featureSuggestion/entities/featureSuggestion.entity.ts
[x]  기능 제안 목록 → 비밀글은 자물쇠 렌더링
[x]  글쓰기 창 → 비밀글 체크 박스
[x]  글쓰기 창 → 비밀글 체크 정보 같이 전달
[x]  기능 제안 개별 보기 → 비밀글 자물쇠 렌더링
[x]  기능 제안 개별 보기 → 좌우 이동 버튼 비밀글 접근 핸들러 동일하게 적용
[x]  글 수정하기 창 → 비밀글 체크 박스 글쓰기와 동일
[x]  Error Snack bar → 비밀글 주인 아닌 경우
=> [TP-SPRINT #2.3] 기능제안 비밀글 기능 - 프론트엔드

client/web/src/assets/constants.ts, client/web/src/organisms/mainpage/main/productHero/ProductHero.tsx, client/web/src/organisms/mainpage/main/solutionCarousel/SolutionCarousel.tsx, client/web/src/organisms/mainpage/main/solutionIntro/SolutionIntro.tsx, client/web/src/organisms/mainpage/main/style/Inquiry.style.ts, client/web/src/organisms/mainpage/main/style/ProductHero.style.ts, client/web/src/organisms/mainpage/main/style/SolutionCarousel.style.ts, client/web/src/organisms/mainpage/main/style/SolutionIntro.style.ts, client/web/src/organisms/mainpage/main/style/WithMedia.style.ts, client/web/src/organisms/mainpage/shared/ProductHero.style.ts, client/web/src/organisms/mypage/layouts/HighlightAnalysisLayout.tsx, client/web/src/organisms/shared/Appbar.tsx, client/web/src/organisms/shared/KakaoTalkButton.tsx, client/web/src/organisms/shared/footer/Footer.tsx, client/web/src/organisms/shared/sub/HeaderLinks.tsx, client/web/src/pages/mainpage/Main.tsx
**반응형 작업 내역**
(1) 모바일용 appbar 추가
(2) md, sm, xs 단위 레이아웃 추가
(3) 중단 캐러셀 부분,, 외부 패키지 이용으로 반응형 수정 에러사항 있음
=> xs 이하의 디스플레이 화면에서는 캐러셀 기능삭제 후 1개 이미지만 렌더링 시킴
=> 메인페이지 반응형 작업 최종

client/web/src/organisms/mypage/stream-analysis/shared/RangeSelectCalendar.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/Calendar.tsx
=> 방송 분석 탭 달력 전환 렉 제거

client/web/src/organisms/mypage/stream-analysis/shared/PeriodSelectPopper.tsx
기존에는 clickAway 리스너가 클릭 할 떄 인식했으나 지금은 클릭하지 않아도 인식되어 계속 열자마자 popper 를 닫아버리는
현상이 발생
클릭 어웨이 리스너 삭제 , 완료 버튼에 close 설정
=> [방송분석 하위탭 - popper 열리지 않는 버그 수정]

client/web/src/organisms/mainpage/notice/NoticeTable.tsx, client/web/src/organisms/shared/HelperPopOver.tsx, client/web/src/pages/mypage/layouts/MypageLayout.style.ts
=> 공지사항 셀크기 수정, 사이드바 zIndex 수정

client/web/src/organisms/mainpage/featureSuggestion/FeatureTable.tsx, client/web/src/organisms/mypage/highlightAnalysis/Calendar.tsx, client/web/src/organisms/mypage/layouts/HighlightAnalysisLayout.style.ts, client/web/src/organisms/mypage/layouts/HighlightAnalysisLayout.tsx, client/web/src/organisms/mypage/stream-analysis/shared/PeriodSelectPopper.tsx, client/web/src/organisms/mypage/stream-analysis/shared/PeriodStreamsList.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/Calendar.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamList.tsx
author 가 외래키임을 인지, author.userId 로 수정
- 최소 길이 부여로 레이아웃 변경되는 버그 수정
- 리스트에서 선택한 방송(카드로 올라간 방송)이 달력에 표시되는 스타일이 마우스 클릭 선택 날짜 스타일 과 구분되도록 변경
- 각 chip 라벨링 적용
- 플랫폼 마크와 방송 제목 한 라인으로 합치고 길어진 방송제목은 2줄이상으로 표현
- 상단 섹션 달력과 리스트 중첩 페이퍼 제거
- 상단 섹션 선택된 방송 중첩 카드 배경 제거
=> [SPRINT 버그 수정]

client/web/src/organisms/shared/footer/Footer.tsx
footer 대표명 삭제 - requested from walker 2020.11.27
=> footer 대표명 삭제

client/web/src/organisms/mypage/stream-analysis/shared/Calendar.tsx, client/web/src/organisms/mypage/stream-analysis/shared/RangeSelectCalendar.style.ts, client/web/src/organisms/mypage/stream-analysis/shared/RangeSelectCalendar.tsx
=> [TP-SPRINT #3] 페이지 렌더링과 동시에 뜨는 "달력 알 수 없는 오류 입니다" 수정

client/web/src/organisms/mainpage/featureSuggestion/FeatureDetail.tsx, client/web/src/organisms/mainpage/featureSuggestion/sub/FeatureReply.tsx, client/web/src/organisms/mainpage/featureSuggestion/sub/FeatureReplyInput.tsx
- 댓글 로딩 컴포넌트 삭제
- 댓글 길이 제한 추가 및 경고 문구 추가
- 댓글에 트루포인트 로고 안보이던 현상 수정
=> [TP-SPRINT #3 BUGFIX] 기능제안 버그 수정

client/web/src/organisms/mainpage/featureSuggestion/FeatureDetail.tsx, client/web/src/organisms/mypage/graph/StackedGraph.tsx, client/web/src/organisms/mypage/stream-analysis/period-vs-period/PeriodCompareSection.style.ts, client/web/src/organisms/mypage/stream-analysis/shared/CheckBoxGroup.tsx, client/web/src/organisms/mypage/stream-analysis/shared/PeriodStreamsList.tsx, client/web/src/organisms/mypage/stream-analysis/shared/RangeSelectCalendar.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/Calendar.tsx
1. 기능제안 개별글 보기 바탕색 화이트 고정
2. 방송분석 stack graph 그리드 색상 theme 따라 바뀌도록 수정
=> [TP - SPRINT #3 버그수정] 다크모드 관련 버그 수정

client/web/src/organisms/mypage/dashboard/UserMetricsSection.tsx
- 그래프에 표현하는 채널 선택 아이콘 버튼이 클릭이 가능한지 애매하여 클릭해보지 않을 듯하다.
- 변경점 ⇒
1. "방송사별 필터링" 제목 추가
2. 버튼 hover 효과를 더 강력하게 변경
=> [TP-SPRINT #3 버그수정] 마이페이지 - 대시보드 수정점

client/web/src/atoms/Dialog/Dialog.tsx, client/web/src/index.tsx, client/web/src/organisms/mainpage/featureSuggestion/FeatureDetail.tsx, client/web/src/organisms/mainpage/main/style/Inquiry.style.ts, client/web/src/organisms/shared/Appbar.tsx, client/web/src/pages/mainpage/FeatureSuggestion.tsx, client/web/src/pages/mainpage/FeatureSuggestionWrite.tsx, client/web/src/pages/mainpage/Introduction.tsx, client/web/src/pages/mainpage/Login.tsx, client/web/src/pages/mainpage/Main.tsx, client/web/src/pages/mainpage/Notice.tsx, client/web/src/pages/mainpage/Regist.tsx, client/web/src/pages/mypage/Dashboard.tsx, client/web/src/pages/mypage/channel-analysis/PeriodAnalysis.tsx, client/web/src/pages/mypage/channel-analysis/VideoAnalysis.tsx, client/web/src/pages/mypage/highlight-analysis/HighlightAnalysis.tsx, client/web/src/pages/mypage/my-office/Settings.tsx, client/web/src/pages/mypage/my-office/Subscribe.tsx, client/web/src/pages/mypage/stream-analysis/PeriodAnalysis.tsx, client/web/src/pages/mypage/stream-analysis/PeriodVsPeriodAnalysis.tsx, client/web/src/pages/mypage/stream-analysis/StreamAnalysis.tsx, client/web/src/pages/others/FindId.tsx, client/web/src/pages/others/FindPassword.tsx, client/web/src/pages/others/PrivacyPolicy.tsx, client/web/src/pages/others/TermsOfUse.tsx, client/web/src/utils/hooks/useScrollTop.tsx
[x ] 캐러셀 실제 데이터가 없다.
⇒ 실제 데이터 받아 넣기 (기획/디자인/마케터 요청)
⇒ luke님께로 일감 이전
[x ]자세히보기 다이얼로그 실제 데이터가 없다.
⇒ 실제 데이터 받아 넣기 (기획/디자인/마케터 요청)
⇒ luke님께로 일감 이전
[o ] 공지사항 / 기능제안 반응형 디자인 적용 X
⇒ 모바일/태블릿 환경에서 메뉴에서 삭제 ( 반응형을 구현 은 차후에 진행)
[o ]  도메인이 바뀌면 스크롤이 맨 위로 올라가지 않음
⇒ 도메인 변경시 스크롤을 TOP 으로 올리도록 수정
[x ]  문의하기 버튼 hover 색상 회색으로 보이는 문제
⇒ HOVER 버튼 색상 추가
⇒ luke님께로 일감 이전
[o ] 문의하기 완료시 취소/확인 버튼 이 렌더링 됨.
- ⇒ "취소" 필요 없으므로 삭제
=> Emma main bug

client/web/src/organisms/mainpage/login/LoginForm.tsx, client/web/src/organisms/mainpage/regist/IdentityVerification.tsx, client/web/src/organisms/mainpage/regist/Stepper.tsx, client/web/src/pages/mainpage/Login.tsx, client/web/src/pages/mypage/layouts/MypageLayout.tsx, client/web/src/utils/contexts/AuthContext.tsx, client/web/src/utils/hooks/useAutoLogin.tsx, server/src/resources/auth/auth.controller.ts
- X, 회원가입 창이 뜨지 않음.
- ⇒ **원인** : 시작 step이 3으로 되어 있었다.
-  ⇒ **수정**: 시작 step을 1로 수정
- 로그인 320px에서 반응형 디자인 문제 있음
- ⇒ **원인**: form의고정 padding 으로 인해, 작은 모바일 화면에서 밀림 현상 발생
- ⇒ **수정** : 모바일에서 form의 padding을 제거
- 로그인은 되나, 마이페이지 입장되고, 곧바로 메인 페이지로 튕기는 현상 있음.
- ⇒ **원인**: useAutoLogin 훅의 loading 처리가 미흡하여 현상 발생.
로딩 ture 이후, 요청이 끝나면 false로 변경이 되어야 하나, 400 error 가 반환되었을 경우에만 false로 변경되도록 처리하여, 끝없는 로딩이 지속되었고, MypageLayout에서 최대 2초 이상 로딩 중인 경우 메인페이지로 이동되도록 처리해 두어 매번 로그인 이후 메인페이지로 이동되었음.
- ⇒ **수정** : 에러를 반환 받았을 때 즉시 로딩을 false로 수정한 이후 에러 코드를 확인하는 절차로 수정
=> [TP-SPRINT #3 버그수정] 회원가입 및 로그인 수정점

collectors/stream-collector/collectors/afreeca-collector.js, collectors/stream-collector/collectors/twitch-collector.js, collectors/stream-collector/collectors/youtube-collector.js, collectors/stream-collector/stream-collector.js, collectors/youtube-live/server/collector.js, collectors/youtube-live/server/func/getActiveStream.js, collectors/youtube-live/server/func/liveCollector.js, collectors/youtube-live/server/func/liveMessageCollector.js, collectors/youtube-live/server/func/loadLiveVideo.js, collectors/youtube-live/server/func/loadMessage.js, collectors/youtube-live/server/func/loadTokens.js, collectors/youtube-live/server/func/setLiveStreamData.js, collectors/youtube-live/server/func/setStreamData.js
- Youtube chat crawler 오류 출력 수정
- 방송정보 수집기 오류 수정
=> [TP-#3] 방송정보 수집기 구현 완료

client/web/src/organisms/mypage/stream-analysis/period-analysis/PeriodAnalysisSection.tsx, client/web/src/organisms/mypage/stream-analysis/period-vs-period/PeriodCompareSection.tsx, client/web/src/organisms/mypage/stream-analysis/shared/PeriodStreamsList.tsx, client/web/src/organisms/mypage/stream-analysis/shared/RangeSelectCalendar.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/Calendar.tsx, client/web/src/organisms/mypage/stream-analysis/stream-vs-stream/StreamCompareSection.tsx, client/web/src/pages/mypage/stream-analysis/PeriodAnalysis.tsx, client/web/src/pages/mypage/stream-analysis/PeriodVsPeriodAnalysis.tsx, client/web/src/pages/mypage/stream-analysis/StreamAnalysis.tsx, server/src/resources/broadcast-info/broadcast-info.controller.ts, server/src/resources/broadcast-info/broadcast-info.service.ts, server/src/resources/category/category.controller.ts, server/src/resources/category/category.service.ts, server/src/resources/stream-analysis/stream-analysis.service.ts
1. 방송 분석 - 프론트 , 백엔드
2. 개인 알림 - 프론트 , 백엔드
3. 일부 작업 그래프 - 프론트, 백엔드
=> [Code Remark] 작업 사항 코드 주석 처리

client/web/src/organisms/mypage/graph/graphsInterface.ts, client/web/src/organisms/mypage/stream-analysis/StreamMetrics.tsx, collectors/stream-collector/collectors/afreeca-collector.js, server/src/resources/stream-analysis/interface/streamsInfo.interface.ts, server/src/resources/stream-analysis/stream-analysis.service.ts, shared/res/StreamAnalysisResType.interface.ts
> 기준 > 비교 : 100% 를 초과하게 많을 때, 기준방송이 비교방송 ~~ 발생수의 2.X 배 입니다.
> 기준 > 비교 : 100%를 초과하지 않게 많을 때, 기준 방송이 비교 방송보다 ~~ 발생 수가 ~% 많습니다
> 기준 < 비교 : 기준 방송이 비교 방송보다 ~ 발생 수가 ~% 적습니다
=> [TP-UPDATE #4.1] 지표별 비교 그래프 수정

client/web/src/organisms/mainpage/main/productHero/ProductHero.tsx
=> 글자 수 보정을 위한 이미지 크기 수정

client/web/src/organisms/mainpage/featureSuggestion/FeatureTable.tsx, client/web/src/organisms/mainpage/featureSuggestion/FeatureWriteForm.tsx, server/src/resources/featureSuggestion/entities/featureSuggestion.entity.ts, server/src/resources/featureSuggestion/entities/featureSuggestionReply.entity.ts
- 기능제안 댓글이 있는경우 삭제되지 않는 현상 수정
=> (댓글도 함께 삭제되도록 관계설정 추가)
- 기능제안 제목 글자수 제한 추가
=> [bug-fix] 기능제안 댓글이 있는경우 삭제되지 않는 현상 수정 (댓글도 함께 삭제되도록 관계설정 추가)

client/admin/src/atoms/ShowSnack.tsx, client/admin/src/organisms/users/sub/DownloadButton.tsx, server/src/resources/highlightPoint/highlight.service.ts
client/admin 수정사항
atoms/ShowSnack.tsx : 에러메시지 보여주기 위해 web/src/atoms/snackbar.ShowSnack.tsx 붙여넣음
organism/users/sub/DownloadButton.tsx : 서버에서 에러 발생시 snackbar 보여주는 함수 추가
server 수정사항
highlightPoint/highlight.service.ts : s3 object의 content가 비어있을 경우 분석된 데이터가 없는것으로 보고 not found에러 발생시킴
=> 관리자페이지 이용자정보 탭 - 편집점 다운로드 데이터 없을 시 에러메시지 보여줌

collectors/stream-collector/Dockerfile, collectors/stream-collector/collectors/afreeca-collector.js, collectors/stream-collector/collectors/twitch-collector.js, collectors/stream-collector/collectors/youtube-collector.js, collectors/stream-collector/dockerignore, collectors/stream-collector/model/connectionPool.js, collectors/stream-collector/package.json, collectors/stream-collector/stream-collector.js
- 개발 및 배포 환경 분기처리
- 변경된 수집기 반영
=> [FIX] dev <= chan-collector

client/web/src/index.tsx, client/web/src/organisms/mainpage/ranking/UserReaction.tsx, client/web/src/organisms/mainpage/ranking/sub/UserReactionListItem.tsx, client/web/src/organisms/shared/Appbar.tsx, client/web/src/pages/mainpage/Ranking.tsx, server/src/app.module.ts, server/src/resources/communityBoard/communityBoard.controller.ts, server/src/resources/userReaction/userReaction.controller.ts, server/src/resources/userReaction/userReaction.module.ts, server/src/resources/userReaction/userReaction.service.ts, server/src/utils/convertIpAddress.ts, shared/dto/userReaction/createUserReaction.dto.ts, shared/interfaces/UserReaction.interface.ts
최근 시청자반응 목록 프론트엔드 작업
- Ranking.tsx   page 컴포넌트 생성
- UserReaction.tsx  organisms 컴포넌트 생성
시청자 반응 최대 50자까지 입력가능
한 화면에 3~4개의 아이템이 보이며, 스크롤해서 최대 10개까지 보여짐
=> Joni 인방랭킹 최근 시청자 반응 목록/입력 (프론트)

client/web/package.json, client/web/src/organisms/mainpage/ranking/UserReactionCard.tsx, client/web/src/organisms/mainpage/ranking/WeeklyViewerRankingCard.tsx, client/web/src/pages/mainpage/Ranking.tsx, server/src/resources/rankings/rankings.service.ts, yarn.lock
인방랭킹 페이지 주간 시청자수 랭킹 꺾은선 그래프 카드 컴포넌트
- 각 플랫폼 별 상위 10인 크리에이터의의 시청자수 데이터 분석된 트위치, 아프리카 시청자수 총합의 꺾은선 그래프
현재 백엔드 코드가 merge되지 않은 상태라 임시데이터로 작성하였으며,
백엔드 코드 merge후 전체 컴포넌트 취합 일감(인방랭킹 페이지 및 레이아웃)에서 백엔드와 연동할 예정입니다!
=> Joni 인방랭킹 최근 시청자수 꺾은선 차트 생성

server/src/resources/cbt/cbt.service.ts
- 기본 비밀번호 변경
- CBT 가입신청 목록 최신순으로 변경
=> [hotfix] CBT 가입 기본 비번 변경 + CBT 가입신청 목록 최신순으로 변경

client/web/src/pages/mainpage/Ranking.tsx
방송인 정보페이지 상단에 캐러셀 컴포넌트가 포함되지 않도록 라우터 구조 수정
방송인 정보페이지에 들어가야 할 컴포넌트는 CreatorEvaluation 내부에 넣으시면 됩니다
=> 방송인 정보페이지 상단에 캐러셀 컴포넌트가 포함되지 않도록 라우터 구조 수정

client/web/src/organisms/mainpage/ranking/sub/DeleteButton.tsx
=> Fix:  인방랭킹 핫시청자반응(작은 게시판) 수정 -> 삭제버튼 마우스 올렸을 때 버튼 안보이는 현상 수정

client/web/src/organisms/mainpage/ranking/StreamEvaluation.tsx, client/web/src/organisms/mainpage/ranking/creatorInfo/CreatorCommentList.tsx, client/web/src/organisms/mainpage/ranking/streamInfo/StreamCommentList.tsx, client/web/src/organisms/mainpage/ranking/streamInfo/StreamInfoCard.tsx, client/web/src/organisms/mainpage/ranking/style/CreatorComment.style.ts, client/web/src/organisms/mainpage/ranking/style/CreatorInfoCard.style.ts, client/web/src/organisms/mainpage/ranking/sub/CommentSortButtons.tsx, client/web/src/organisms/shared/footer/Footer.tsx, server/src/resources/broadcast-info/broadcast-info.module.ts, server/src/resources/broadcast-info/entities/streamComment.entity.ts, server/src/resources/broadcast-info/entities/streamCommentVote.entity.ts, server/src/resources/broadcast-info/streamComment.controller.ts, server/src/resources/broadcast-info/streamComment.service.ts, server/src/resources/broadcast-info/streamCommentVote.service.ts, shared/interfaces/StreamComments.interface.ts, shared/res/StreamCommentResType.interface.ts
- 방송정보 페이지에 댓글 컴포넌트 추가(방송인 프로필 페이지 컴포넌트와 컨트롤러, 서비스 복붙함)
- 방송정보 페이지 상단 좋아요 눌러서 로딩중일 때 카드 컴포넌트가 보이지 않는 부분 수정
- footer 로고 이미지 깨진것 변경, 배경색 변경
=> 방송 정보 페이지 댓글 추가

client/web/src/organisms/mainpage/ranking/streamInfo/StreamInfoCard.tsx
방송정보페이지 - 아프리카 TV 방송국으로 이동되지 않는 현상 수정
=> Fix: 방송정보페이지 - 아프리카 TV 방송국으로 이동되지 않는 현상 수정

client/web/src/organisms/mypage/highlightAnalysis/HighChart.tsx
chart컴포넌트 Umount 시 plotband 제거 함수 이동
=> Fix highlight chart

client/web/src/index.tsx, client/web/src/organisms/mainpage/communityBoard/share/BoardTitle.tsx, client/web/src/organisms/mainpage/ranking/ToptenCard.tsx, client/web/src/organisms/mainpage/ranking/style/RankingPage.style.ts, client/web/src/organisms/mainpage/ranking/style/RatingList.style.ts, client/web/src/organisms/mainpage/ranking/style/TopTenCard.style.ts, client/web/src/organisms/mainpage/ranking/style/TopTenList.style.ts, client/web/src/organisms/mainpage/ranking/style/UserReactionCard.style.ts, client/web/src/organisms/mainpage/ranking/sub/HeaderDecoration.tsx, client/web/src/organisms/mainpage/ranking/sub/RatingsListItem.tsx, client/web/src/organisms/mainpage/youtubeHighlight/list/HighlightListContainer.tsx, client/web/src/organisms/mainpage/youtubeHighlight/list/PostList.tsx, client/web/src/organisms/shared/Appbar.tsx, client/web/src/pages/mainpage/YoutubeHighlightList.tsx
- 상단 앱바 '로고' 눌렀을 때 [인방랭킹 페이지]로 이동
- 기존의 [메인페이지]는 'about us' (새로 생성한 메뉴아이템)눌렀을 때 이동
변경 전 앱바
[TRUE P]   인방랭킹 | 유투브편집점 | 공지사항 | 기능제안 | 자유게시판
변경 후 앱바
[TRUE P]   인방랭킹 | 자유게시판 | 공지사항 | 기능제안 | 유튜브편집점 | About us
=> 메인화면을 인방랭킹 페이지로 수정

client/admin/src/organisms/creatorManage/CreatorDetail.tsx, client/admin/src/organisms/creatorManage/CreatorRatingForAdmin.tsx, server/src/resources/creatorRatings/creatorRatings.controller.ts, server/src/resources/creatorRatings/creatorRatings.service.ts
- 관리자 페이지 > 크리에이터 관리 탭에 평점매기기 부분 추가
- 관리자용 평점 라우터와 서비스 함수 생성
=> 관리자페이지>크리에이터관리> 평점매기기 추가

client/web/src/index.tsx, client/web/src/pages/others/UpdatingPage.tsx
- index.tsx 에서 <Index>컴포넌트 대신 <UpdatingPage> 컴포넌트 렌더링 하도록 함
- <UpdatingPage> : 테스트서버의 디비 데이터 옮기는 동안 업데이트 중임을 알릴 화면
=> 업데이트 중입니다 페이지

client/web/src/organisms/shared/footer/Footer.tsx, server/src/resources/auth/auth.controller.ts
부산광역시 금정구 장전온천천로 51 테라스파크 3층 313호 와일트루 -> 와일트루 부분 삭제
=> hotfix - 푸터 사무실 주소 수정

client/web/src/organisms/mainpage/ranking/CreatorDetails.tsx, client/web/src/organisms/mainpage/ranking/StreamEvaluation.tsx, client/web/src/organisms/mainpage/ranking/creatorInfo/CreatorInfoCard.tsx, client/web/src/organisms/mainpage/ranking/streamInfo/StreamInfoCard.tsx
/ranking/creator/ㅁㄴㅇ라ㅓㅁㄴㅇ 
/ranking/103825127/stream/ㅁㄴㅇㄹ
와 같이 잘못된 creatorId, streamId로 접근시
메인페이지로 이동시킴
=> [TP v3.1 - 추가수정] 존재하지 않는 creatorId, streamId로 접근시 처리

client/web/src/atoms/User/AvatarWithName.tsx, client/web/src/interfaces/LoginUser.ts, client/web/src/organisms/mainpage/ranking/topten/TrendsBarChart.tsx, client/web/src/organisms/mainpage/regist/Paper.tsx, client/web/src/organisms/mainpage/regist/RegistForm.tsx, client/web/src/organisms/mainpage/regist/Stepper.reducer.ts, client/web/src/organisms/mypage/my-office/sub/PasswordChangeDialog.tsx, client/web/src/organisms/mypage/userInfo/LoginUserProfile.tsx, client/web/src/organisms/mypage/userInfo/UpdateProfileImageDialog.tsx, client/web/src/utils/contexts/AuthContext.tsx, server/src/resources/users/users.controller.ts, server/src/resources/users/users.service.ts
로버트님 피드백 수정사항 반영
- 필수약관
- 서비스 이용약관, 개인정보 처리방침만 있고 수신동의 ~ 내용은 제거
- 이용약관의 일부가 창으로 미리보여져있는 형태로 수정 (읽어야만 체크할 수 있는 절차 x)
- 회원정보 입력
- 닉네임 중복확인 추가
- 비밀번호는 특수문자가 없어도 상관없게 "영문 숫자 구성 8자-20자"로 수정
- 마이페이지
- 닉네임 수정시 중복확인 추가
- 인방랭킹
- 7일간 꺾은선 그래프 애니메이션 렉 → 애니메이션 해제
=> [TP#3.1] test 서버에 피드백 수정사항 반영

aws/cdk/lib/dev-test/truepoint-dev-stack.ts, aws/cdk/lib/prod/truepoint-production-stack.ts, server/prod-task-definition.json, server/test-task-definition.json
- parameter store에 필요한 파라미터 추가
- cdk에서 개발, 배포환경 파라미터 호출하는 코드 추가
- task-definition에서 컨테이너에 환경변수 주입하는 코드 추가
=> [TP #3.1+] 배포를 위한 cdk, task-definition 변경

package.json, server/src/admin-panel/components/community-post-link.tsx, server/src/admin-panel/components/community-post-platform-label.tsx, server/src/admin-panel/config.ts, server/src/admin-panel/resources/stream.resource.ts, server/src/admin-panel/resources/user.resource.ts
- package.json 에 @admin-bro/** 패키지 nohoist 추가
- 유저, 방송정보 리소스 숨김
- 게시글 잘못된 링크 수정
=> [테스트서버 배포] adminbro 적용

client/web/src/organisms/mainpage/ranking/sub/FirstPlaceCreators.tsx, server/src/resources/creatorRatings/creatorRatings.service.ts, server/src/resources/rankings/rankings.service.ts, server/src/resources/users/users.service.ts
- 캐러셀 평점이 소수점 2자리 이상 나오는 문제 수정
- 캐러셀 외 평점 값을 모두 동일하게 소수점 2자리까 조회하도록 수정
=> 평점 수치 표현 수정

client/web/src/organisms/mainpage/ranking/sub/RatingsListItem.tsx, server/src/resources/creatorRatings/creatorRatings.service.ts
- nickname 값이 null인지 확인하는 절차 추가
- rating 관련 서비스 에러 트라이 캐치 구문 추가
=> [Hotfix] nickname 이 null로 들어갈 때 처리

client/web/src/organisms/mainpage/ranking/sub/FirstPlaceCreators.tsx, server/src/resources/creatorRatings/creatorRatings.service.ts, server/src/resources/rankings/rankings.service.ts, server/src/resources/users/users.service.ts
- 캐러셀 부분 평점 소수점 2자리까지 표시되도록 수정
- 평점 구하는 쿼리에 round 적용
=> [hotfix] 평점 소수점 2자리까지만 나오도록 수정

client/web/src/organisms/mainpage/ranking/style/CreatorComment.style.ts, client/web/src/organisms/mainpage/ranking/sub/CommentItem.tsx
댓글 가시성을 높이기 위한 수정 적용
- 댓글 컴포넌트 데스크탑 사이즈에서 16px로 증가 (버튼 글자와 좋아요 숫자도 2px정도 증가)
- 좋아요 싫어요 숫자 크기 증가, 굵기, 색 변경
=> [hotfix] 방송인 프로필 페이지 댓글 스타일 수정

client/admin/src/data/knownCreators210419.json
Robert  오후 2:48
{
“creatorId”: “216473763",
“nickname”: “얏따”
},
여유되실때 추가를 부탁드립니다
=> Add: 크리에이터 creatorId 정보 추가요청 처리 => master

client/admin/src/organisms/creatorManage/RegisterCreatorDialog.tsx, client/web/src/atoms/CustomPagination.tsx, client/web/src/organisms/mainpage/communityBoard/list/BoardContainer.tsx, client/web/src/organisms/mainpage/communityBoard/postView/RepliesContainer.tsx, client/web/src/organisms/mainpage/communityBoard/postView/RepliesSection.tsx, client/web/src/organisms/mainpage/communityBoard/style/CommunityBoardList.style.tsx, client/web/src/organisms/mainpage/ranking/search/CreatorSearchTable.tsx, client/web/src/organisms/mainpage/youtubeHighlight/list/HighlightListTable.tsx, client/web/src/organisms/mypage/userInfo/MyPosts.tsx
- 방송인 검색, 자유게시판, 유투브 편집점, 내정보관리 - 내가 쓴글, 댓글 목록에서 사용되는 페이지네이션 컴포넌트 통일
- 관리자페이지 - 방송인 등록시 아프리카 프로필 이미지 주소 오타 수정
=> 페이지네이션 컴포넌트 통일 외

client/web/public/index.html
open graph 수정 필요 #248
- 오픈그래프 이미지 새 로고로 변경
- 오픈그래프 문구 수정 
- 수정 전 : "1인 방송 데이터 분석 솔루션, 트루포인트"
- 수정 후 : "시청자 반응, 유튜브 편집점 분석 플랫폼 - 트루포인트"
=> 오픈그래프 이미지, 문구 수정

client/web/public/index.html
=> TP 배포요청 (오픈그래프 수정)

client/web/src/utils/hooks/useScoresHistoryChartOptions.ts
원점수가 10점 초과시 그래프 상 10점 위치에 표시, 툴팁에도 10점으로 표기
=> [hotfix] 감정점수 10점 초과시 10점으로 표시

client/web/src/organisms/mainpage/regist/RegistForm.tsx, client/web/src/organisms/mainpage/regist/Stepper.reducer.ts, server/src/config/mailer.config.ts
기획 요청으로 트루포인트 회원 가입 화면에서 '이름' 입력칸 삭제
=> [배포요청] 회원가입 화면에서 '이름' 입력칸 삭제

client/web/package.json, client/web/src/utils/hooks/useScoresHistoryChartOptions.ts, server/package.json, server/src/app.module.ts, server/src/config/configOptions.ts, server/src/config/configValidation.ts, yarn.lock
Config 모듈 유효성 검사 #304 를 보고 
schemaValidation 옵션을 추가해보았습니다
=> configModule Joi schemaValidation 추가

client/web/package.json, client/web/src/organisms/mainpage/regist/RegistForm.tsx, client/web/src/organisms/mainpage/regist/Stepper.reducer.ts, server/package.json, server/src/app.module.ts, server/src/config/configOptions.ts, server/src/config/mailer.config.ts, yarn.lock
- 트루포인트 웹 회원가입 폼에서 '이름' 입력칸 삭제(로버트님 요청)
- config module 유효성 검사 추가(env 파일 joi schema validation적용)
=> [TP 3.22.1 배포] 회원가입 폼 이름인풋 삭제

client/web/src/organisms/mainpage/login/FindIdForm.tsx, client/web/src/pages/others/GetTemporaryPassword.tsx, server/src/resources/users/users.controller.ts, server/src/resources/users/users.service.ts, yarn.lock
회원가입 폼에서 이름 입력칸 삭제함(#311)에 따라
-  아이디 찾기, 비밀번호 찾기 화면에서도 이름 입력칸 삭제
- 아이디 찾기, 유저확인 핸들러에서 이름 파라미터 삭제
=> [TP v3.22.2 배포요청] 아이디, 비밀번호 찾기에서 이름 부분 삭제

server/.adminbro/.entry.js, server/package.json, server/src/admin-panel/admin-panel.options.ts, server/src/admin-panel/components/creator-link.tsx, server/src/admin-panel/resources/index.ts, server/src/admin-panel/resources/ratings.resource.ts, server/src/resources/creatorRatings/entities/creatorRatings.entity.ts, yarn.lock
- /server package.json dependency에 joi 추가
- 관리자 페이지(adminbro) 에 평점테이블 추가(기획 요청 - 평점 매긴 사람과 점수 조회)
=> server package.json  dependency에 joi 추가, 관리자 페이지(adminbro) 평점 테이블 추가

server/.adminbro/.entry.js, server/package.json, server/src/admin-panel/admin-panel.options.ts, server/src/admin-panel/components/creator-link.tsx, server/src/admin-panel/resources/index.ts, server/src/admin-panel/resources/ratings.resource.ts, server/src/resources/creatorRatings/entities/creatorRatings.entity.ts, yarn.lock
서버 배포 에러(package.json dependencies에 joi 패키지 추가 안함)로 적용되지 않은 기능 적용 위함
- config module 유효성 확인
- 회원가입 폼 이름 입력창 삭제
- 아이디, 비밀번호 찾기 화면에서 이름 입력창 삭제
- 아이디, 유저 확인 핸들러에서 name 프로퍼티 삭제
=> [tp v3.22.2 배포요청] joy 패키지 추가

client/web/src/index.tsx, client/web/src/organisms/mainpage/ranking/RankingMain.tsx, client/web/src/organisms/shared/Appbar.tsx, client/web/src/pages/mypage/Dashboard.tsx, client/web/src/pages/mypage/UserInfoPage.tsx
tp 서비스 축소 및 유지보수 최소화를 위해 자유게시판, 공지사항, 기능제안 게시판 닫음
- index.tsx 에서 자유게시판, 공지사항, 기능제안 관련 라우터 주석처리
- Appbar에서 자유게시판,공지사항,기능제안 링크 주석처리
- 마이페이지에서 내가 쓴글, 내가 쓴 댓글부분 주석처리
- 유투브 편집점 확인 대시보드에서 공지사항 부분 주석처리
=> [배포요청] tp 서비스 축소 - 자유게시판, 공지사항, 기능제안 관련 기능 숨김(주석처리)

client/web/src/organisms/mainpage/main/intro/Intro.tsx
=> 트루포인트 소개 영상 변경
